apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: kube-jit-api
data:
  clusters: |
    # - name: gke-cluster
    #   host: https://gke-api-server-endpoint
    #   ca: <b64 encoded ca cert>
    #   insecure: false
    #   tokenSecret: gke-sa-token
    # - name: aks-cluster
    #   host: https://aks-api-server-endpoint
    #   ca: <b64 encoded ca cert>
    #   insecure: false
    #   tokenSecret: aks-sa-token
    - name: kind-jit-ext
      host: 'https://host.docker.internal:53166'
      tokenSecret: kind-jit-ext-sa-token
      insecure: false
      ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTDFZbEtMbWVQOUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1qRXhOVEV4TkRWYUZ3MHpOVEEwTVRreE5URTJORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURpVXQzZ3UzSTVrNS9vcXJRT2RvRFdMdHZyQXplaUtKZ2tMLy9OcGJPZXRNdzI0V2g2Ym16eHRKaDMKZDBFejIyTEp0V25RMm5RQjlWVjlsR3M3MUFWd1MwaGtSbU8rL21aTE9GaUJsYndwYzRTQTR1NVNHYmd4OVQxVQprV3kzNEl2REFCMW5hVzZBZFBZNTdQKytQS0VSYmRzQTVWS2RFMkNRVk9lakYxdGthczZCREx2bXp2MHlwTFZ5CnZFdEwyMW8vNGxEY3Q3R0ZtMTJJRDErM3h2VHdaWXRhVk5zbllSZVBPbHJBTUJlZ1ZIeFVkR3pvUjRuclY5NTIKd3E3SGV1K0gvSlVBZk53dDFlbVpsMmtEekpld3hDenNRSHRWMFl5T3o3SEMzTm9wNU9hYUw1d0J3TlBXb3JsRwpIUkVQRGJHR3hIUkpvRDlRcXBXMXlyVXJHbDlUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUcWtVYTJZSmo1ZFliZmxtSFM2UFB4d2dVUFR6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUdRREVxbVp6dgpKK1k5cU5OWngwUC9WVjZTRTRXMEJCZlBPblhrbjYzU3BJVk5WR3I0OHU4UHdDY05VQ244MEpzZjlwdUlFNmtvCmxNRnJYdnp0ekx3bU5KblZObXVySjJoT3Bjd0UyWTkvQThQdFpwK0d6MHFSRmdZTVp0RDV6TWNSWldnbjJzRFAKVlFLc2RRQURadERubXRoVThLelZtR2lnMmVvMzRsdlRmbXlYcFVJRjNHZ1NTNnJFWVR0VmhUWUd0MTVCTlBnSApDTzdjRjM3dGxqMEhtVEEyc01mbGNsMnBNbVlHN1NIejJBcEl2ZmJ4bENHbTRMUmpVVE1HVGQzakkvbm9TK0h3CkQ4Z2FjWE0vdTJYMFhReFZHOEVKWGJzT0JrYWM4Z3FmMXJuT3dIRXd4ci9iSEN3UlNOL2VTc1c0cWtCNGwrUzIKbEdGVDRZUFZ5alpRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
