apiVersion: jit.kubejit.io/v1
kind: JitRequest
metadata:
  labels:
    app.kubernetes.io/name: kube-jit-operator
    app.kubernetes.io/managed-by: kustomize
  name: jitrequest-sample
spec:
  # TODO(user): Add fields here
