apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-jit-operator.fullname" . }}-jitgroupcache-editor-role
  labels:
  {{- include "kube-jit-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitgroupcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitgroupcaches/status
  verbs:
  - get