apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-jit-operator.fullname" . }}-jitrequest-admin-role
  labels:
  {{- include "kube-jit-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests
  verbs:
  - '*'
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests/status
  verbs:
  - get