apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-jit-operator.fullname" . }}-kubejitconfig-viewer-role
  labels:
  {{- include "kube-jit-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - jit.kubejit.io
  resources:
  - kubejitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jit.kubejit.io
  resources:
  - kubejitconfigs/status
  verbs:
  - get