apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-jit-web.fullname" . }}
  labels:
    {{- include "kube-jit-web.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;

      #access_log /dev/stdout withauthheaders;
      
      # Web
      location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          try_files $uri $uri/ /index.html =404;
      }
      
      # API
      location /kube-jit-api {
          proxy_pass {{ .Values.nginx.apiUrl }};
          client_max_body_size 20m;
          proxy_read_timeout 60s;
      }

      include /etc/nginx/extra-conf.d/*.conf;
    }
