apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-kube-jit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jitrequest-editor-role
subjects:
- kind: User
  name: 8ea97dcb-a67f-438a-95b2-0de055bd797e # Managed Identity's Object Principal ID
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-kube-jit-cache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-jit-kube-jit-operator-jitgroupcache-viewer-role
subjects:
- kind: User
  name: 8ea97dcb-a67f-438a-95b2-0de055bd797e # Managed Identity's Object Principal ID
