# This rule is not used by the project kube-jit-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the jit.kubejit.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-jit-operator
    app.kubernetes.io/managed-by: kustomize
  name: jitrequest-editor-role
rules:
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests/status
  verbs:
  - get
