---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests
  - kubejitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests/finalizers
  - kubejitconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - jit.kubejit.io
  resources:
  - jitrequests/status
  - kubejitconfigs/status
  verbs:
  - get
  - patch
  - update
