config:
  allowedRoles:
    - name: edit
    - name: admin
  
  platformApproverTeams:
    - name: "jit approvers"
      id: 12769788
    - name: "jit approvers google"
      id: jit-approvers-google@samirtahir.dev
    - name: "jit approvers azure"
      id: 3252cdf5-2db4-413c-b34f-459ea439397e
    - name: "Team C"
      id: 123456
  
  cors:
    allowOrigins:
      - "http://host.docker.internal:5173"
      - "http://localhost:5173"
  
  clusters:
    - name: autopilot-cluster-2
      type: gke
      projectID: sacred-entry-304212
      region: europe-west2

  callbackHostOverride: http://localhost:8589
  
  allowedDomain: "samirtahir.dev"         # For Google/Azure
  allowedGithubOrg: "samirtahir91-org"            # For GitHub
  
  oauth:
    provider: "github"
    clientID: Iv23likSg0AQoOUi18q7
    redirectUri: "http://localhost:5173/"
    clientSecretKeyRef: ghAppClientSecret

db:
  host: my-postgres-postgresql.default.svc.cluster.local
  connTimeout: "10"
  name: postgres
  port: "5432"
  sslMode: "prefer"
  timezone: "Europe/London"
  maxOpenConns: "50"
  maxIdleConns: "20"
  connMaxLifetime: "10m"
  connMaxIdleTime: "15m"

image:
  repository: samirtahir91076/kube-jit-api
  tag: v1.1.8
  imagePullPolicy: Always

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: kube-jit-api@sacred-entry-304212.iam.gserviceaccount.com
