apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-kube-jit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jitrequest-editor-role
subjects:
- kind: ServiceAccount
  name: kube-jit
  namespace: kube-jit