apiVersion: v1
kind: Secret
metadata:
  name: kube-jit-api-secrets
  namespace: kube-jit-api
type: Opaque
data:
  dbUser: cG9zdGdyZXMK
  dbPassword: bXlzZWNyZXRwYXNzd29yZAo=
  hmac-secret: bXlzZWNyZXRwYXNzd29yZAo=
  cookie-secret: bXlzZWNyZXRwYXNzd29yZAo=
  ghAppClientSecret: bXlzZWNyZXRwYXNzd29yZAo=