apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    {{- include "kube-jit-api.labels" . | nindent 4 }}
data:
  apiConfig: |
    clusters:
      {{- $allowedClusterKeys := include "allowedClusterKeys" . }}
      {{- range .Values.config.clusters }}
        {{- $invalidKeys := list }}
        {{- range $key, $value := . }}
          {{- if not (include "has" (list $allowedClusterKeys $key)) }}
            {{- $invalidKeys = append $invalidKeys $key }}
          {{- end }}
        {{- end }}
        {{- if gt (len $invalidKeys) 0 }}
          {{- fail (printf "Invalid keys found: %v" $invalidKeys) }}
        {{- end }}
      {{- end }}
      {{- toYaml .Values.config.clusters | nindent 4 }}
    allowedRoles:
      {{- $allowedRoleKeys := include "allowedRoleKeys" . }}
      {{- range .Values.config.allowedRoles }}
        {{- $invalidKeys := list }}
        {{- range $key, $value := . }}
          {{- if not (include "has" (list $allowedRoleKeys $key)) }}
            {{- $invalidKeys = append $invalidKeys $key }}
          {{- end }}
        {{- end }}
        {{- if gt (len $invalidKeys) 0 }}
          {{- fail (printf "Invalid keys found: %v" $invalidKeys) }}
        {{- end }}
      {{- end }}
      {{- toYaml .Values.config.allowedRoles | nindent 4 }}
    allowedApproverTeams:
      {{- $allowedApproverTeamKeys := include "allowedApproverTeamKeys" . }}
      {{- range .Values.config.allowedApproverTeams }}
        {{- $invalidKeys := list }}
        {{- range $key, $value := . }}
          {{- if not (include "has" (list $allowedApproverTeamKeys $key)) }}
            {{- $invalidKeys = append $invalidKeys $key }}
          {{- end }}
        {{- end }}
        {{- if gt (len $invalidKeys) 0 }}
          {{- fail (printf "Invalid keys found: %v" $invalidKeys) }}
        {{- end }}
      {{- end }}
      {{- toYaml .Values.config.allowedApproverTeams | nindent 4 }}
