# Default values for kube-jit-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Nginx configuration
# apiUrl: Configurable API URL for the backend service. Defaults to "kube-jit-api.default.svc.cluster.local".
# resolver: Configurable DNS resolver. Defaults to the Kubernetes DNS service (kube-dns.kube-system.svc.cluster.local).
# resolverValid: Configurable DNS cache validity period. Defaults to 30s.
# clientMaxBodySize: Configurable maximum body size for requests. Defaults to 20m.
# proxyConnectTimeout: Configurable timeout for establishing a connection to the upstream server. Defaults to 10s.
# proxySendTimeout: Configurable timeout for sending requests to the upstream server. Defaults to 15s.
# proxyReadTimeout: Configurable timeout for reading responses from the upstream server. Defaults to 20s.
nginx:
  apiUrl: "kube-jit-api.kube-jit-api.svc.cluster.local" # Default Kubernetes service name
  resolver: "kube-dns.kube-system.svc.cluster.local" # Default Kubernetes DNS resolver
  resolverValid: "10s" # DNS resolution refresh interval
  clientMaxBodySize: "20m" # Default max body size
  proxyConnectTimeout: "10s" # Default proxy connect timeout
  proxySendTimeout: "15s" # Default proxy send timeout
  proxyReadTimeout: "20s" # Default proxy read timeout

replicaCount: 1

image:
  repository: kube-jit-web
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  containerPort: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: []
  hosts: []
    # - host: kube-jit.example.com
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
