apiVersion: v1
kind: Service
metadata:
  name: kube-jit-api-lb
  namespace: kube-jit-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: kube-jit-api
    app.kubernetes.io/name: kube-jit-api
  sessionAffinity: None
  type: LoadBalancer
