basePath: /kube-jit-api
definitions:
  models.NamespaceApprovalInfo:
    properties:
      approved:
        type: boolean
      approverID:
        type: string
      approverName:
        type: string
      groupID:
        type: string
      groupName:
        type: string
      namespace:
        type: string
    type: object
  models.RequestWithNamespaceApprovers:
    properties:
      CreatedAt:
        type: string
      DeletedAt:
        type: string
      ID:
        type: integer
      UpdatedAt:
        type: string
      approverIDs:
        items:
          type: string
        type: array
      approverNames:
        items:
          type: string
        type: array
      clusterName:
        type: string
      email:
        type: string
      endDate:
        type: string
      fullyApproved:
        type: boolean
      justification:
        type: string
      namespaceApprovals:
        items:
          $ref: '#/definitions/models.NamespaceApprovalInfo'
        type: array
      namespaces:
        items:
          type: string
        type: array
      notes:
        type: string
      roleName:
        type: string
      startDate:
        type: string
      status:
        type: string
      userID:
        type: string
      username:
        type: string
      users:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: Self-service Kubernetes RBAC JIT Requests with Google/Azure/Github
    Oauth.
  title: Kube-JIT API
  version: "1.0"
paths:
  /history:
    get:
      consumes:
      - application/json
      description: |-
        Returns the latest JIT requests for a user with optional limit and date range.
        Requires one or more cookies named kube_jit_session_<number> (e.g., kube_jit_session_0, kube_jit_session_1).
        Pass split cookies in the Cookie header, for example:
        -H "Cookie: kube_jit_session_0=${cookie_0};kube_jit_session_1=${cookie_1}"
      parameters:
      - description: 'Session cookies (multiple allowed, names: kube_jit_session_0,
          kube_jit_session_1, etc.)'
        in: header
        name: Cookie
        required: true
        type: string
      - description: User ID
        in: query
        name: userID
        type: string
      - description: Username
        in: query
        name: username
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.RequestWithNamespaceApprovers'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get JIT requests for a user
      tags:
      - records
swagger: "2.0"
